### ISSUE TITLE
football predictions

### ISSUE THREAD

**Issue by SoccerCashUK** [DJDarkCyber/SportsWinnerPredictor#1]
Internal Server Error: /predictFootball
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Roaming\Python\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Acer\SportsWinnerPredictor\sportsPredictor\views.py", line 89, in predictFootball
    home_team = home_team.readlines()
  File "C:\Program Files\Python310\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x83 in position 1273: character maps to <undefined>

**Comment by DJDarkCyber** [comment]
This is an encoding error. In windows the file should be opened by specifying encoding type. It has been fixed in new commit. Thanks for reporting this issue
